[package]
name = "poggers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
windows = {version = "0.39.0",features = [
    "Win32_Foundation"
], optional = true}

[features]
default = ["win"]
win = ["windows"]