[package]
name = "poggers"
version = "0.1.0"
edition = "2021"
description = "memory lib"
license = "GPL-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
windows = {version = "0.39.0",features = [
    "Win32_System_Threading","Win32_Foundation","Win32_System_LibraryLoader",
    "Win32_System_Diagnostics_ToolHelp", "Win32_System_Diagnostics_Debug",
    "Win32_System_Memory", "Win32_System_ProcessStatus"
], optional = true}
anyhow = "1.0.65"
thiserror = "1.0.35"
[features]
default = ["win"]
win = ["windows"]