[package]
name = "poggers-derive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
proc-macro2= "1.0.43"
quote = "1.0.21"
syn = {version = "1.0.99", features = ["full"]}
windows = {version = "0.39", features = [
    "Win32_System_SystemServices", "Win32_Foundation"
],optional = true}
proc-macro-crate = "1.2.1"

[features]
default = ["win"]
win = ["windows"]